import './globals.css'
import AuthContextProvider from '@/context/authcontext'
import ExperienceContextProvider from '@/context/expContext'
export const metadata = {
  title: 'Resume Revamp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-exo">
        <AuthContextProvider>
          <ExperienceContextProvider>
            {children}
          </ExperienceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
